project:
  type: website
  output-dir: docs

website:
  title: "marine-ecologist"
  site-url: https://marine-ecologist.github.io/
  navbar:
    left:
      - text: "Code"
        icon: code
        href: code.qmd
      - text: "Projects"
        icon: cube
        menu:
          - text: "---"
          - text: "coralseed - a realtime interactive visualisation of the world's oceans"
            icon: compass
            href: https://marine-ecologist.github.io/coralseed/
          - text: "reefspawn - an interactive visualisation of heatwaves on the Great Barrier Reef"
            icon: moon
            href: https://marine-ecologist.github.io/reefspawn/
          - text: "DHW - an R package for calculating sea surface temperature (SST) metrics"
            icon: thermometer-half
            href: https://marine-ecologist.github.io/dhw/
          - text: "coastalwaves - a realtime interactive visualisation of the world's oceans"
            icon: wind
            href: https://marine-ecologist.github.io/coastalwaves/
          - text: "coralcolors - colour palettes for R and ggplot2 based on scleractinian corals"
            icon: palette
            href: https://marine-ecologist.github.io/coralcolors/
          - text: "---"
          - text: "Oceans - a realtime interactive visualisation of the world's oceans"
            icon: circle
            href: https://marine-ecologist.github.io/oceans/
          - text: "dhw3 - an interactive visualisation of heatwaves on the Great Barrier Reef"
            icon: fire
            href: https://marine-ecologist.github.io/dhw3/
          - text: "---"
          - text: "DCIEM - a dev app and package for calculating dive algorithms"
            icon: calculator
            href: https://marine-ecologist.github.io/dciem/
          - text: "Sensorflow - development of low-cost tiltmeters"
            icon: shuffle
            href: https://github.com/marine-ecologist/sensorflow/
      - text: "Publications"
        menu:
          - text: "Google Scholar profile"
            icon: google
            href: "https://scholar.google.com.au/citations?user=g_m1R7IAAAAJ&hl=en"
          - text: "Publication summary"
            icon: bar-chart
            href: publication_summary.qmd
          - text: "Publication list"
            icon: stack-overflow
            href: publications.qmd
      - text: "Images"
        menu:
          - text: "2024/2025 Great Barrier Reef bleaching events"
            icon: fire
            href: <ADD-URL>   # TODO
      - text: "Contact"
        href: contact.qmd
      - text: "GitHub"
        icon: github
        href: https://github.com/marine-ecologist

format:
  html:
    toc: false
    code-fold: true
    fig-cap-location: bottom
